"use server";

import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Json } from "@/types/database";
import type { ContentSourceMeta } from "@/lib/content-source";

const VIDEO_BUCKET = "collaboration-videos";

// STEP39: the raw video bytes are uploaded directly browser -> Storage (see
// useVideoManager) since they can be tens of MB — well past what a server
// action/API route body limit should comfortably carry (photos, by
// contrast, are resized to small JPEGs first, which is why uploadPhoto in
// ../photos/actions.ts can take the bytes through a server action). This
// action only registers the already-uploaded object's metadata, mirroring
// uploadPhoto's row shape as closely as the extra video fields allow.
export async function registerVideo(input: {
  collaborationId: string;
  storagePath: string;
  originalFilename: string | null;
  mimeType: string | null;
  fileSizeBytes: number;
  durationSeconds: number;
  width: number;
  height: number;
}) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "로그인이 필요합니다." };

  const { count } = await supabase
    .from("collaboration_videos")
    .select("id", { count: "exact", head: true })
    .eq("collaboration_id", input.collaborationId);

  const { data, error } = await supabase
    .from("collaboration_videos")
    .insert({
      collaboration_id: input.collaborationId,
      user_id: user.id,
      storage_path: input.storagePath,
      original_filename: input.originalFilename,
      mime_type: input.mimeType,
      file_size_bytes: input.fileSizeBytes,
      duration_seconds: input.durationSeconds,
      width: input.width,
      height: input.height,
      display_order: count ?? 0,
    })
    .select("id")
    .single();

  if (error) return { error: `저장 실패: ${error.message}` };

  revalidatePath(`/collaborations/${input.collaborationId}/content`);
  return { success: true as const, id: data.id };
}

export async function reorderVideos(collaborationId: string, orderedIds: string[]) {
  const supabase = await createSupabaseServerClient();
  await Promise.all(
    orderedIds.map((id, index) =>
      supabase.from("collaboration_videos").update({ display_order: index }).eq("id", id),
    ),
  );
  revalidatePath(`/collaborations/${collaborationId}/content`);
}

export async function deleteVideo(collaborationId: string, videoId: string, storagePath: string) {
  const supabase = await createSupabaseServerClient();
  await supabase.storage.from(VIDEO_BUCKET).remove([storagePath]);
  await supabase.from("collaboration_videos").delete().eq("id", videoId);
  revalidatePath(`/collaborations/${collaborationId}/content`);
}

// STEP39 item 22: the whole Reels project (scene order/trim/captions/style/
// target duration/guide snapshot) lives in contents.generation_input jsonb
// for a platform='REELS' row — the exact same pattern STEP36 established for
// the blog's BlogMeta. No dedicated reels_projects table.
export type ReelsCaptionStyle = {
  preset: "basic" | "clean" | "emphasis";
  position: "top" | "middle" | "bottom";
  size: "small" | "medium" | "large";
};

export type ReelsScene = {
  id: string; // `photo:<collaboration_photos.id>` or `video:<collaboration_videos.id>`
  mediaType: "photo" | "video";
  mediaId: string;
  included: boolean;
  trimStart?: number;
  trimEnd?: number;
  durationSeconds: number;
  caption: string;
  captionVisible: boolean;
};

export type ReelsProject = {
  scenes: ReelsScene[];
  targetDurationSeconds: 15 | 30 | 60;
  captionStyle: ReelsCaptionStyle;
  guideTextAtGeneration?: string | null;
  // STEP46: 네이버 클립 전용. 사용자가 네이버 앱에서 직접 업로드할 때
  // 복사해서 쓸 게시 문구와 해시태그. 릴스 프로젝트에는 설정되지 않는다
  // (릴스 캡션은 기존 Instagram 패널이 따로 담당한다).
  publishCopy?: string;
  hashtags?: string[];
  // STEP42: set only when this project was generated by "이 카드뉴스로 릴스
  // 만들기" (a deterministic, AI-free mapping from an existing CarouselProject
  // — see ../carousel/from-carousel.ts). Never set for a from-scratch AI 릴스
  // 만들기.
  sourceMeta?: ContentSourceMeta;
};

// STEP46: platform 을 파라미터로 받되 기본값은 기존과 동일한 "REELS" 라서
// 기존 릴스 호출부(ReelsStudio, from-carousel)는 한 글자도 바뀌지 않는다.
// 네이버 클립은 platform='NAVER_CLIP' 로 저장되므로 같은 협업의 릴스
// 프로젝트와 DB row 자체가 분리된다 — 클립을 만들어도 릴스 프로젝트를
// 덮어쓸 수 없다(STEP46 항목 4).
export type ShortFormPlatform = "REELS" | "NAVER_CLIP";

export async function saveReelsProject(input: {
  collaborationId: string;
  contentId?: string | null;
  project: ReelsProject;
  platform?: ShortFormPlatform;
}) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "로그인이 필요합니다." };

  if (input.contentId) {
    const { error } = await supabase
      .from("contents")
      .update({ generation_input: input.project as unknown as Json })
      .eq("id", input.contentId);
    if (error) return { error: `저장 실패: ${error.message}` };
    revalidatePath(`/collaborations/${input.collaborationId}/content`);
    return { success: true as const, id: input.contentId };
  }

  const { data, error } = await supabase
    .from("contents")
    .insert({
      collaboration_id: input.collaborationId,
      user_id: user.id,
      platform: input.platform ?? "REELS",
      status: "DRAFT",
      ai_provider: "claude",
      generation_input: input.project as unknown as Json,
    })
    .select("id")
    .single();

  if (error) {
    // STEP46: contents.platform 은 CHECK 제약이라, 0025 마이그레이션이 아직
    // 적용되지 않은 DB에서는 NAVER_CLIP insert 가 제약 위반으로 떨어진다.
    // 사용자에게 raw Postgres 메시지를 그대로 노출하지 않고(STEP44에서 정리한
    // 원칙) 무엇이 필요한지 한국어로 알려준다.
    if (input.platform === "NAVER_CLIP" && error.message.includes("contents_platform_check")) {
      return {
        error:
          "네이버 클립 저장에 필요한 DB 업데이트가 아직 적용되지 않았습니다. 관리자에게 문의해주세요. (마이그레이션 0025 필요)",
      };
    }
    return { error: `저장 실패: ${error.message}` };
  }
  revalidatePath(`/collaborations/${input.collaborationId}/content`);
  return { success: true as const, id: data.id };
}
